const grammar = {
    terminals: [
      'the', 'a', 'an',
      'man', 'woman', 'boy', 'girl', 'dog', 'cat', 'child', 'teacher', 'student', 'bird', 'car', 'bus', 'mat', 'table',
      'house', 'tree', 'book', 'chair', 'fish', 'horse', 'baby', 'doctor', 'friend', 'river', 'boat', 'plane', 'desk',
      'big', 'small', 'red', 'blue', 'happy', 'sad', 'fast', 'slow', 'young', 'old', 'black',
      'tall', 'short', ' cyan', 'yellow', 'angry', 'calm', 'loud', 'quiet', 'new', 'bright', 'dark',
      'runs', 'walks', 'sleeps', 'sits', 'jumps', 'flies', 'drives',
      'swims', 'eats', 'reads', 'writes', 'sings', 'dances', 'climbs', 'waits',
      'on', 'under', 'over', 'near', 'behind', 'beside',
      'above', 'below', 'around', 'through', 'across', 'inside', 'outside',
      'and', 'with', 'by', 'in',
      'or', 'but'
    ],
  
    nonTerminals: [
      'S', 'NounPhrase', 'VerbPhrase', 'Determiner', 'Noun', 'Adjective', 'AdjectiveList', 'Verb', 'PrepositionalPhrase', 'Preposition', 'Conjunction', 'CompoundNounPhrase'
    ],
  
    parseTable: {
      S: {
        the: ['NounPhrase', 'VerbPhrase'],
        a: ['NounPhrase', 'VerbPhrase'],
        an: ['NounPhrase', 'VerbPhrase']
      },
  
      NounPhrase: {
        the: ['Determiner', 'AdjectiveList', 'Noun', 'CompoundNounPhrase'],
        a: ['Determiner', 'AdjectiveList', 'Noun', 'CompoundNounPhrase'],
        an: ['Determiner', 'AdjectiveList', 'Noun', 'CompoundNounPhrase']
      },
  
      CompoundNounPhrase: {
        and: ['Conjunction', 'NounPhrase'],
        or: ['Conjunction', 'NounPhrase'],
        but: ['Conjunction', 'NounPhrase'],
        with: ['PrepositionalPhrase'],
        by: ['PrepositionalPhrase'],
        in: ['PrepositionalPhrase'],
        on: ['PrepositionalPhrase'],
        under: ['PrepositionalPhrase'],
        over: ['PrepositionalPhrase'],
        near: ['PrepositionalPhrase'],
        behind: ['PrepositionalPhrase'],
        beside: ['PrepositionalPhrase'],
        above: ['PrepositionalPhrase'],
        below: ['PrepositionalPhrase'],
        around: ['PrepositionalPhrase'],
        through: ['PrepositionalPhrase'],
        across: ['PrepositionalPhrase'],
        inside: ['PrepositionalPhrase'],
        outside: ['PrepositionalPhrase'],
        runs: ['ε'],
        walks: ['ε'],
        sleeps: ['ε'],
        sits: ['ε'],
        jumps: ['ε'],
        flies: ['ε'],
        drives: ['ε'],
        swims: ['ε'],
        eats: ['ε'],
        reads: ['ε'],
        writes: ['ε'],
        sings: ['ε'],
        dances: ['ε'],
        climbs: ['ε'],
        waits: ['ε'],
        $: ['ε']
      },
  
      VerbPhrase: {
        runs: ['Verb', 'PrepositionalPhrase'],
        walks: ['Verb', 'PrepositionalPhrase'],
        sleeps: ['Verb', 'PrepositionalPhrase'],
        sits: ['Verb', 'PrepositionalPhrase'],
        jumps: ['Verb', 'PrepositionalPhrase'],
        flies: ['Verb', 'PrepositionalPhrase'],
        drives: ['Verb', 'PrepositionalPhrase'],
        swims: ['Verb', 'PrepositionalPhrase'],
        eats: ['Verb', 'PrepositionalPhrase'],
        reads: ['Verb', 'PrepositionalPhrase'],
        writes: ['Verb', 'PrepositionalPhrase'],
        sings: ['Verb', 'PrepositionalPhrase'],
        dances: ['Verb', 'PrepositionalPhrase'],
        climbs: ['Verb', 'PrepositionalPhrase'],
        waits: ['Verb', 'PrepositionalPhrase']
      },
  
      Determiner: {
        the: ['the'],
        a: ['a'],
        an: ['an']
      },
  
      AdjectiveList: {
        big: ['Adjective', 'AdjectiveList'],
        small: ['Adjective', 'AdjectiveList'],
        red: ['Adjective', 'AdjectiveList'],
        blue: ['Adjective', 'AdjectiveList'],
        happy: ['Adjective', 'AdjectiveList'],
        sad: ['Adjective', 'AdjectiveList'],
        fast: ['Adjective', 'AdjectiveList'],
        slow: ['Adjective', 'AdjectiveList'],
        young: ['Adjective', 'AdjectiveList'],
        old: ['Adjective', 'AdjectiveList'],
        black: ['Adjective', 'AdjectiveList'],
        tall: ['Adjective', 'AdjectiveList'],
        short: ['Adjective', 'AdjectiveList'],
        green: ['Adjective', 'AdjectiveList'],
        yellow: ['Adjective', 'AdjectiveList'],
        angry: ['Adjective', 'AdjectiveList'],
        calm: ['Adjective', 'AdjectiveList'],
        loud: ['Adjective', 'AdjectiveList'],
        quiet: ['Adjective', 'AdjectiveList'],
        new: ['Adjective', 'AdjectiveList'],
        bright: ['Adjective', 'AdjectiveList'],
        dark: ['Adjective', 'AdjectiveList'],
        man: ['ε'],
        woman: ['ε'],
        boy: ['ε'],
        girl: ['ε'],
        dog: ['ε'],
        cat: ['ε'],
        child: ['ε'],
        teacher: ['ε'],
        student: ['ε'],
        bird: ['ε'],
        car: ['ε'],
        bus: ['ε'],
        mat: ['ε'],
        table: ['ε'],
        house: ['ε'],
        tree: ['ε'],
        book: ['ε'],
        chair: ['ε'],
        fish: ['ε'],
        horse: ['ε'],
        baby: ['ε'],
        doctor: ['ε'],
        friend: ['ε'],
        river: ['ε'],
        boat: ['ε'],
        plane: ['ε'],
        desk: ['ε']
      },
  
      Adjective: {
        big: ['big'],
        small: ['small'],
        red: ['red'],
        blue: ['blue'],
        happy: ['happy'],
        sad: ['sad'],
        fast: ['fast'],
        slow: ['slow'],
        young: ['young'],
        old: ['old'],
        black: ['black'],
        tall: ['tall'],
        short: ['short'],
        green: ['green'],
        yellow: ['yellow'],
        angry: ['angry'],
        calm: ['calm'],
        loud: ['loud'],
        quiet: ['quiet'],
        new: ['new'],
        bright: ['bright'],
        dark: ['dark']
      },
  
      Noun: {
        man: ['man'],
        woman: ['woman'],
        boy: ['boy'],
        girl: ['girl'],
        dog: ['dog'],
        cat: ['cat'],
        child: ['child'],
        teacher: ['teacher'],
        student: ['student'],
        bird: ['bird'],
        car: ['car'],
        bus: ['bus'],
        mat: ['mat'],
        table: ['table'],
        house: ['house'],
        tree: ['tree'],
        book: ['book'],
        chair: ['chair'],
        fish: ['fish'],
        horse: ['horse'],
        baby: ['baby'],
        doctor: ['doctor'],
        friend: ['friend'],
        river: ['river'],
        boat: ['boat'],
        plane: ['plane'],
        desk: ['desk']
      },
  
      Verb: {
        runs: ['runs'],
        walks: ['walks'],
        sleeps: ['sleeps'],
        sits: ['sits'],
        jumps: ['jumps'],
        flies: ['flies'],
        drives: ['drives'],
        swims: ['swims'],
        eats: ['eats'],
        reads: ['reads'],
        writes: ['writes'],
        sings: ['sings'],
        dances: ['dances'],
        climbs: ['climbs'],
        waits: ['waits']
      },
  
      PrepositionalPhrase: {
        on: ['Preposition', 'NounPhrase'],
        under: ['Preposition', 'NounPhrase'],
        over: ['Preposition', 'NounPhrase'],
        near: ['Preposition', 'NounPhrase'],
        behind: ['Preposition', 'NounPhrase'],
        beside: ['Preposition', 'NounPhrase'],
        in: ['Preposition', 'NounPhrase'],
        with: ['Preposition', 'NounPhrase'],
        by: ['Preposition', 'NounPhrase'],
        above: ['Preposition', 'NounPhrase'],
        below: ['Preposition', 'NounPhrase'],
        around: ['Preposition', 'NounPhrase'],
        through: ['Preposition', 'NounPhrase'],
        across: ['Preposition', 'NounPhrase'],
        inside: ['Preposition', 'NounPhrase'],
        outside: ['Preposition', 'NounPhrase'],
        and: ['ε'],
        or: ['ε'],
        but: ['ε'],
        $: ['ε']
      },
  
      Preposition: {
        on: ['on'],
        under: ['under'],
        over: ['over'],
        near: ['near'],
        behind: ['behind'],
        beside: ['beside'],
        in: ['in'],
        with: ['with'],
        by: ['by'],
        above: ['above'],
        below: ['below'],
        around: ['around'],
        through: ['through'],
        across: ['across'],
        inside: ['inside'],
        outside: ['outside']
      },
  
      Conjunction: {
        and: ['and'],
        or: ['or'],
        but: ['but']
      }
    }
  };
  
  export default grammar;